name: Application

on:
  push:
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.22.5'

      - name: Build
        working-directory: app
        run: |
          go build .

      - name: Build docker container and push
        id: docker_build
        uses: docker/build-push-action@v6
        env:
          RELEASE_VERSION: ${{ steps.next.outputs.version }}
        with:
          context: ./app
          file: ./app/Dockerfile
          platforms: linux/amd64
          push: false
          tags: |
            pharndt/fritzboxmqtt:latest
