name: Java CI

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 8

      - name: Build with Maven
        env:
          USENAME: ${{github.actor}}
          PASSWORD: ${{ secrets.GITHUB_TOKEN }}
        run: mvn -B package verify --file src/pom.xml --settings .github/workflows/settings.xml
